"""initial finance v0.1 schema

Revision ID: 34f4e80340ee
Revises: 
Create Date: 2026-09-22 11:32:18.657054

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f4e80340ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('account_type', sa.Enum('CASH', 'INVESTMENT', 'LIABILITY', name='accounttype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='accountstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.CheckConstraint('currency_code = upper(currency_code)', name='ck_accounts_currency_code_upper'),
    sa.CheckConstraint('length(currency_code) = 3', name='ck_accounts_currency_code_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accounts_currency_code', 'accounts', ['currency_code'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('affected_entity_type', sa.String(), nullable=False),
    sa.Column('affected_entity_id', sa.Uuid(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approval_status', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('capital_buckets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bucket_role', sa.Enum('GENERAL', 'TAX_RESERVE', name='bucketrole', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('is_protected', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='capitalbucketstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capital_buckets_account_id', 'capital_buckets', ['account_id'], unique=False)
    op.create_index('ix_capital_buckets_bucket_role', 'capital_buckets', ['bucket_role'], unique=False)
    op.create_table('financial_targets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('target_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('currency_code = upper(currency_code)', name='ck_financial_targets_currency_code_upper'),
    sa.CheckConstraint('length(currency_code) = 3', name='ck_financial_targets_currency_code_length'),
    sa.ForeignKeyConstraint(['metric_key'], ['financial_metrics.key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_key', 'effective_from', name='uq_financial_targets_metric_effective_from')
    )
    op.create_index('ix_financial_targets_metric_key', 'financial_targets', ['metric_key'], unique=False)
    op.create_table('monthly_targets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('target_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('currency_code = upper(currency_code)', name='ck_monthly_targets_currency_code_upper'),
    sa.CheckConstraint('length(currency_code) = 3', name='ck_monthly_targets_currency_code_length'),
    sa.CheckConstraint('month >= 1 AND month <= 12', name='ck_monthly_targets_month_range'),
    sa.ForeignKeyConstraint(['metric_key'], ['financial_metrics.key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_key', 'year', 'month', 'effective_from', name='uq_monthly_targets_metric_year_month_effective_from')
    )
    op.create_index('ix_monthly_targets_metric_key', 'monthly_targets', ['metric_key'], unique=False)
    op.create_index('ix_monthly_targets_year_month', 'monthly_targets', ['year', 'month'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_type', sa.Enum('NORMAL', 'OPENING_BALANCE', 'TRANSFER', name='transactionkind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'VOIDED', name='transactionstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('correction_of', sa.Uuid(), nullable=True),
    sa.Column('metric_key', sa.String(), nullable=True),
    sa.Column('transfer_group_id', sa.Uuid(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.CheckConstraint('currency_code = upper(currency_code)', name='ck_transactions_currency_code_upper'),
    sa.CheckConstraint('length(currency_code) = 3', name='ck_transactions_currency_code_length'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['correction_of'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['metric_key'], ['financial_metrics.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_account_id', 'transactions', ['account_id'], unique=False)
    op.create_index('ix_transactions_metric_key', 'transactions', ['metric_key'], unique=False)
    op.create_index('ix_transactions_occurred_at', 'transactions', ['occurred_at'], unique=False)
    op.create_index('ix_transactions_transfer_group_id', 'transactions', ['transfer_group_id'], unique=False)
    op.create_table('bucket_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bucket_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('entry_type', sa.Enum('CASH_LINKED', 'REALLOCATION', name='entrytype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('originating_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('reallocation_group_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(entry_type = 'CASH_LINKED' AND originating_transaction_id IS NOT NULL) OR (entry_type = 'REALLOCATION' AND reallocation_group_id IS NOT NULL)", name='ck_bucket_allocations_entry_type_linkage'),
    sa.CheckConstraint('currency_code = upper(currency_code)', name='ck_bucket_allocations_currency_code_upper'),
    sa.CheckConstraint('length(currency_code) = 3', name='ck_bucket_allocations_currency_code_length'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['bucket_id'], ['capital_buckets.id'], ),
    sa.ForeignKeyConstraint(['originating_transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bucket_allocations_account_id', 'bucket_allocations', ['account_id'], unique=False)
    op.create_index('ix_bucket_allocations_bucket_id', 'bucket_allocations', ['bucket_id'], unique=False)
    op.create_index('ix_bucket_allocations_reallocation_group_id', 'bucket_allocations', ['reallocation_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bucket_allocations_reallocation_group_id', table_name='bucket_allocations')
    op.drop_index('ix_bucket_allocations_bucket_id', table_name='bucket_allocations')
    op.drop_index('ix_bucket_allocations_account_id', table_name='bucket_allocations')
    op.drop_table('bucket_allocations')
    op.drop_index('ix_transactions_transfer_group_id', table_name='transactions')
    op.drop_index('ix_transactions_occurred_at', table_name='transactions')
    op.drop_index('ix_transactions_metric_key', table_name='transactions')
    op.drop_index('ix_transactions_account_id', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_monthly_targets_year_month', table_name='monthly_targets')
    op.drop_index('ix_monthly_targets_metric_key', table_name='monthly_targets')
    op.drop_table('monthly_targets')
    op.drop_index('ix_financial_targets_metric_key', table_name='financial_targets')
    op.drop_table('financial_targets')
    op.drop_index('ix_capital_buckets_bucket_role', table_name='capital_buckets')
    op.drop_index('ix_capital_buckets_account_id', table_name='capital_buckets')
    op.drop_table('capital_buckets')
    op.drop_table('financial_metrics')
    op.drop_table('audit_logs')
    op.drop_index('ix_accounts_currency_code', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
